# Generated by Django 5.2.4 on 2025-07-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('idUsuarioCriador', models.CharField(max_length=100)),
                ('nomeUsuario', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
